WIP: Merge aw-watcher-bash-preexec into aw-watcher-bash.sh
Otto-AA/aw-watcher-bash pull request #6
Opened 2018-07-07 09:53 UTC by johan-bjareholt

Works, but have not tested properly yet and still don't fully understand the implementation so there is likely multiple errors.
Don't have time to work on it anymore today (but hopefully will tomorrow) so I open this review to let @Otto-AA be able to see the changes in the mean time.

2018-07-07 16:26 UTC, Otto-AA requested changes
Seems to work fine :)

Here are some changes I would make. If you don't agree with them, just say it. Some are maybe personal preferences.

Here is the file in the edited version: https://repl.it/repls/AthleticShallowFactorial

2018-07-07 16:28 UTC, Otto-AA commented
Btw, I won't be able to code for a few weeks, starting next Tuesday. So don't be surprised if I don't react to pull-requests/...

2018-07-08 11:58 UTC, johan-bjareholt commented on aw-watcher-bash.sh
> +current_shell=$(ps -p "$$" | tail -n 1 | awk '{ print $4 }')
Fixed

2018-07-08 11:58 UTC, johan-bjareholt commented on aw-watcher-bash.sh
> +function escape_quotes() {
Fixed

2018-07-08 11:58 UTC, johan-bjareholt commented on aw-watcher-bash.sh
> +function send_event() {
Fixed

2018-07-08 11:58 UTC, johan-bjareholt commented on aw-watcher-bash.sh
> +    function add_arg() {
Fixed

2018-07-08 11:58 UTC, johan-bjareholt commented on aw-watcher-bash.sh
> +    add_arg '--pid' "$2"
Fixed

2018-07-08 11:58 UTC, johan-bjareholt commented on aw-watcher-bash.sh
> +aw_watcher_terminal_preclose() {
Fixed

2018-07-08 11:58 UTC, johan-bjareholt commented on aw-watcher-bash.sh
> -echo "$message" >> "$logfile"
Just thought it was unnecessary, might become large after a few months. We could possibly keep it commented out though to easily enable debugging.

2018-07-08 11:59 UTC, johan-bjareholt commented
> Btw, I won't be able to code for a few weeks, starting next Tuesday. So don't be surprised if I don't react to pull-requests/...

Alright, thanks for all the great work!
I hope we will be able to work some more later on :)

2018-07-08 12:31 UTC, Otto-AA commented on aw-watcher-bash.sh
> -echo "$message" >> "$logfile"
Good idea :)

2018-07-08 12:41 UTC, Otto-AA commented
> Alright, thanks for all the great work!
I hope we will be able to work some more later on :)

And thank you for the feedback you gave me 👍 
As this is my first project I'm working on together with others, it is really appreciated.

2018-07-08 12:41 UTC, Otto-AA approved these changes

2018-07-08 12:51 UTC, Otto-AA commented on aw-watcher-bash.sh
> +    pipe_message_args+=("$1 \"$(escape_quotes "$2")\"")
Would be nice if you could intend it a little bit more :)

2018-07-08 12:52 UTC, Otto-AA commented
Is there still something you want to change (as it is "WIP") or is it ready to be merged?

2018-07-08 15:11 UTC, johan-bjareholt commented
Don't think so no

2018-07-08 15:38 UTC, merged